## The Imams of the School

**3rd Century:**  
And among the most important transmitters of the old madhab are: Imam Ahmad ibn Hanbal, Abu Thawr, al-Zafarani, al-Karabisi.

**Students of al-Shafi'i (transmitters of the school):**  
Al-Muzani, al-Buwayti, al-Rabi' al-Muradi, Harmalah, al-Rabi' al-Jizi, Yunus ibn Abd al-Ala.

---

**4th Century:**  
Ibn Surayj, al-Qaffal al-Kabir al-Shashi, Abu Hamid al-Isfarayini, al-Ishtakhri, al-Marwazi, Ibn Abi Hurayrah, Ibn al-Qass.

---

**5th Century:**  
Al-Mawardi, Abu Ishaq al-Shirazi, Abu Muhammad al-Juwayni and his son, Imam al-Haramayn, Bahyaqi, al-Bandaniji, al-Muhamali, al-Qaffal al-Saghir al-Marwazi, al-Qadi Husayn, al-Furani, al-Masudi, Ibn al-Sabbagh, al-Mutawalli.

---

**6th Century:**  
Al-Ghazali (Hujjat al-Islam), al-Shashi, al-Baghawi, and al-Imrani.

---

**7th Century:**  
Ibn al-Salah, al-Qazwini, al-Izz ibn Abd al-Salam, the two great Imams al-Nawawi and al-Rafi'i (the two masters of the school), Ibn al-Firkah, Ibn Daqiq al-Id.

---

**8th Century:**  
Ibn al-Rif'ah, al-Taqi al-Subki, al-Qamuli, al-Isnawi, al-Adhra'i, al-Bulqini, Ibn al-Mulaqqin, al-Zarkashi, Ibn al-Naqib, al-Sharif al-Barizi, al-Muhibb al-Tabari.

---

**9th Century:**  
Al-Wali al-Iraqi, al-Taqi al-Hisni, al-Shihab ibn Raslan (author of *Safwat al-Zubad*), Ibn Qadi Shuhbah, Ibn al-Muzajjad, al-Damiri, al-Jalal al-Mahalli, al-Afqahisi, Ibn al-Muqri, Abd Allah ibn Abd al-Rahman Ba-Fadal.

---

**10th Century:**  
Imam al-Jalal al-Suyuti, Shaykh al-Islam Zakariyya al-Ansari, al-Khatib al-Shirbini, al-Shihab al-Ramli, his son al-Shams, Ibn Hajar al-Haytami, Abd Allah ibn Umar Ba-Makhrama, Ibn Qasim al-Abbadi, Ba Qushayr, and ibn-Ziyad.

---

**11th Century:**  
Burhan al-Birmawi, Ali al-Shabaramilsi, and others.

---

**12th Century:**  
 Al-Bajuri, al-Sharqawi, al-Bujayrarmi, Abd Allah ibn Husayn Bal Faqih, Abd Allah ibn Ahmad Basudan, Sa’id ibn Muhammad Ba’ishin, Abd al-Rahman ibn Sulayman al-Ahdal, Ali Basabrin, others.---

**13th Century:**  
Sayyid Alawi ibn Ahmad al-Saqqaf, Ahmad ibn Zayni Dahlan, Bakri Shatta, Abd al-Rahman al-Mashhur, Abu Bakr ibn Abd al-Rahman ibn Shihab, Abu Bakr ibn Ahmad al-Khatib, Abd Allah Ba Jammah, Abd Allah ibn Umar al-Shatiri, Ahmad ibn Umar al-Shatiri, Abd al-Rahman ibn Abdid Allah al-Saqqaf, Muhammad ibn Hadi al-Saqqaf, Muhammad ibn Salim ibn Hafiz, and others.

**14th Century and Later:**  
A large number of scholars appeared and authored works in the later centuries. May Allah be pleased with them all. The scholars of the madhhab wrote prolifically — so much so that it is difficult to even count all their writings.

This is exemplified in the work of Imam al-Subki, *Tabaqat al-Shafi'iyyah al-Kubra*, which spans ten volumes. It demonstrates the vast number of scholars in the Shafi'i tradition, the range of their service, and how nearly every field of Islamic knowledge has Shafi'i representatives.

---

**Among the Usulis (Legal Theorists):**  
Al-Juwayni (author of *al-Burhan*), al-Ghazali (author of *al-Mustasfa*), al-Razi (author of *al-Mahsool*), Taj al-Subki (author of *Jam' al-Jawami*), al-Baydawi (author of *Minhaj al-Usul*), and others — their books are among the most significant in the field of usul al-fiqh.

---

**Among the Hadith Scholars:**  
The hadith masters include: al-Daraqutni, Ibn Khuzaymah, Ibn Hibban, Abu Nu'aym, ibn al-Mundhir, al-Khatabi, Khatib al-Baghdadi, al-Hafidh al-Bayhaqi (author of *al-Sunan*), Zayn al-Iraqi (author of *Alfiyyah* in Hadith), al-Haythami (author of *Majma' al-Zawa'id*), Ibn Hajar al-Asqalani (author of *Fath al-Bari*), and others.

---

**Among the Historians and Biographers:**  
Ibn 'Asakir (author of *Tarikh Dimashq*), al-Dhahabi (author of *Siyar A'lam al-Nubala'*), al-Safadi (author of *al-Wafi*), Ibn Kathir (author of *al-Bidayah wa al-Nihayah*), Ibn al-Athir (author of *al-Kamil*), and others.

---

**Among the Theologians (Mutakallimeen):**  
Al-Halimi (author of *Shu'ab al-Iman*), Abd al-Qahir al-Baghdadi, Fakhr al-Din al-Razi (author of *al-Matalib al-'Aliyah*), and others in the field of theology and doctrine. Others include 'Adul al-Ayji, al-Aamidi, 'Ulaa al-Baji, al-Asfahani, al-Taftazani, and others.

---

**Among the Quran Commentators:**  
Al-Mawardi (author of the great *Tafsir*), al-Khazin, al-Baghawi (author of *Ma'alim al-Tanzil*).

---

**Among the Quran Reciters:**  
Al-Ja'bari, Ibn al-Jazari (author of *al-Nashr*), al-Shihab al-Qastallani.

---

**Among the Linguists and Grammarians:**  
Abu Hayyan al-Andalusi, Ibn Malik (author of *al-Alfiyyah*), Ibn Aqil, Ibn Hisham, al-Fayruzabadi (author of *al-Qamus*), and others.

---

**Among the Sufi Masters:**  
Al-Qushayri (author of *al-Risalah al-Qushayriyyah*), Imam al-Ghazali, Imam Abd Allah ibn Alawi al-Haddad.

---

And countless other imams and scholars who contributed to the sciences and branches of knowledge across the Islamic tradition.
